<?php

$customterm = array(

  'custom_types' => array(
    'wp-type-contacts' => array(
      'labels' => array(
        'name' => 'UkuuPeople',
        'singular_name' => 'Human',
        'add_new' => 'Add New',
        'add_new_item' => 'Add New %s',
        'edit_item' => '%s',
        'new_item' => 'New %s',
        'view_item' => 'View %s',
        'search_items' => 'Search %s',
        'not_found' => 'No %s found',
        'not_found_in_trash' => 'No %s found in Trash',
        'parent_item_colon' => 'Parent text',
        'all_items' => 'People',
      ),
      'slug' => 'wp-type-contacts',
      'description' => 'Wordpress custom contacts which will be synced with user',
      'icon' => 'admin-users',
      'public' => 'public',
      'menu_position' =>'',
      'menu_icon' =>'',
      'taxonomies' => array(
        'category' => 1,
        'wp-type-group' => 1,
        'wp-type-tags' => 1,
      ),
      'supports' => array(
        'title' => 1,
      ),
      'rewrite' => array(
        'enabled' => 1,
        'custom' => 'normal',
        'slug' => '',
        'with_front' => 1,
        'feeds' => 1,
        'pages' => 1,
      ),
      'has_archive' => 1,
      'show_in_menu' => 1,
      'show_in_menu_page' => '',
      'show_ui' => 1,
      'publicly_queryable' => 1,
      'can_export' => 1,
      'show_in_nav_menus' => 1,
      'query_var_enabled' => 1,
      'query_var' => '',
      'permalink_epmask' => 'EP_PERMALINK',
      'wpcf-post-type' => '',
      'post_relationship' => array(
        'has' => array(
          'wp-type-activity' => 1
        )
      )
    ),
    'wp-type-activity' => array(
      'labels' => array(
        'name' => 'Touchpoints',
        'singular_name' => 'Touchpoint',
        'add_new' => 'Add New',
        'add_new_item' => 'Add New %s',
        'edit_item' => 'Edit %s',
        'new_item' => 'New %s',
        'view_item' => 'View %s',
        'search_items' => 'Search %s',
        'not_found' => 'No %s found',
        'not_found_in_trash' => 'No %s found in Trash',
        'parent_item_colon' => 'Parent text',
        'all_items' => 'People',
      ),
      'slug' => 'wp-type-activity',
      'description' => 'Activities for wordpress contacts/users',
      'icon' => 'clipboard',
      'public' => 'public',
      'menu_position' =>'',
      'menu_icon' =>'',
      'supports' => array(
         'title' => 1,
      ),
      'rewrite' => array(
        'enabled' => 1,
        'custom' => 'normal',
        'slug' => '',
        'with_front' => 1,
        'feeds' => 1,
        'pages' => 1,
      ),
      'has_archive' => 1,
      'show_in_menu' => 1,
      'show_in_menu_page' => '',
      'show_ui' => 1,
      'publicly_queryable' => 1,
      'can_export' => 1,
      'show_in_nav_menus' => 1,
      'query_var_enabled' => 1,
      'query_var' => '',
      'permalink_epmask' => 'EP_PERMALINK',
      'wpcf-post-type' => '',
      'post_relationship' => array(
        'belongs' => array(
          'wp-type-contacts' => 1
        )
      )
    )
  ),

  'custom_taxonomies' => array(
    'wp-type-group' => array(
      'labels' => array(
        'name' => 'Tribes',
        'singular_name' => 'Tribe',
        'search_items' => 'Search %s',
        'popular_items' => 'Popular %s',
        'all_items' => 'All %s',
        'parent_item' => 'Parent %s',
        'parent_item_colon' => 'Parent %s:',
        'edit_item' => 'Edit %s',
        'update_item' => 'Update %s',
        'add_new_item' => 'Add New %s',
        'new_item_name' => 'New %s Name',
        'separate_items_with_commas' => 'Separate %s with commas',
        'add_or_remove_items' => 'Add or remove %s',
        'choose_from_most_used' => 'Choose from the most used %s',
        'menu_name' => '%s',
      ),
      'slug' => 'wp-type-group',
      'description' => 'Wordpress groups for wp-conatcts',
      'public' => 'public',
      'supports' => array(
        'wp-type-contacts' => 1,
      ),
      'hierarchical' => 'hierarchical',
      'rewrite' => array(
        'enabled' => 1,
        'slug' => '',
        'with_front' => 1,
        'hierarchical' => 1,
      ),
      'show_ui' => 1,
      'show_in_nav_menus' => 1,
      'show_tagcloud' => 1,
      'query_var_enabled' => 1,
      'query_var' => '',
      'update_count_callback' => '',
    ),
    'wp-type-tags' => array(
      'labels' => array(
        'name' => 'Tags',
        'singular_name' => 'Tag',
        'search_items' => 'Search %s',
        'popular_items' => 'Popular %s',
        'all_items' => 'All %s',
        'parent_item' => 'Parent %s',
        'parent_item_colon' => 'Parent %s:',
        'edit_item' => 'Edit %s',
        'update_item' => 'Update %s',
        'add_new_item' => 'Add New %s',
        'new_item_name' => 'New %s Name',
        'separate_items_with_commas' => 'Separate %s with commas',
        'add_or_remove_items' => 'Add or remove %s',
        'choose_from_most_used' => 'Choose from the most used %s',
        'menu_name' => '%s',
      ),
      'slug' => 'wp-type-tags',
      'description' => 'Tags for wordpress contacts',
      'public' => 'public',
      'supports' => array(
        'wp-type-contacts' => 1,
      ),
      'hierarchical' => 'flat',
      'rewrite' => array(
        'enabled' => 1,
        'slug' => '',
        'with_front' => 1,
        'hierarchical' => 1,
      ),

      'show_ui' => 1,
      'show_in_nav_menus' => 1,
      'show_tagcloud' => 1,
      'query_var_enabled' => 1,
      'query_var' => '',
      'update_count_callback' => '',
    ),
    'wp-type-contacts-subtype' => array(
      'labels' => array(
        'name' => 'Contact Types',
        'singular_name' => 'Contact Type',
        'search_items' => 'Search %s',
        'popular_items' => 'Popular %s',
        'all_items' => 'All %s',
        'parent_item' => 'Parent %s',
        'parent_item_colon' => 'Parent %s:',
        'edit_item' => 'Edit %s',
        'update_item' => 'Update %s',
        'add_new_item' => 'Add New %s',
        'new_item_name' => 'New %s Name',
        'separate_items_with_commas' => 'Separate %s with commas',
        'add_or_remove_items' => 'Add or remove %s',
        'choose_from_most_used' => 'Choose from the most used %s',
        'menu_name' => '%s',
      ),
      'slug' => 'wp-type-contacts-subtype',
      'description' => 'Contact types for user/wp contacts eg Individual, organization, etc.',
      'public' => 'public',
      'supports' => array(
        'wp-type-contacts' => 1,
      ),
      'hierarchical' => 'hierarchical',
      'rewrite' => array(
        'enabled' => 1,
        'slug' => '',
        'with_front' => 1,
        'hierarchical' => 1,
      ),

      'show_ui' => 1,
      'show_in_nav_menus' => 1,
      'show_tagcloud' => 1,
      'query_var_enabled' => 1,
      'query_var' => '',
      'update_count_callback' => '',
    ),
    'wp-type-activity-types' => array(
      'labels' => array(
        'name' => 'Touchpoint Types',
        'singular_name' => 'Touchpoint Type',
        'search_items' => 'Search %s',
        'popular_items' => 'Popular %s',
        'all_items' => 'All %s',
        'parent_item' => 'Parent %s',
        'parent_item_colon' => 'Parent %s:',
        'edit_item' => 'Edit %s',
        'update_item' => 'Update %s',
        'add_new_item' => 'Add New %s',
        'new_item_name' => 'New %s Name',
        'separate_items_with_commas' => 'Separate %s with commas',
        'add_or_remove_items' => 'Add or remove %s',
        'choose_from_most_used' => 'Choose from the most used %s',
        'menu_name' => '%s',
      ),
      'slug' => 'wp-type-activity-types',
      'description' => 'Touchpoint types',
      'public' => 'public',
      'supports' => array(
        'wp-type-activity' => 1,
      ),
      'hierarchical' => 'hierarchical',
      'rewrite' => array(
        'enabled' => 1,
        'slug' => '',
        'with_front' => 1,
        'hierarchical' => 1,
      ),

      'show_ui' => 1,
      'show_in_nav_menus' => 1,
      'show_tagcloud' => 1,
      'query_var_enabled' => 1,
      'query_var' => '',
      'update_count_callback' => '',
    )
  ),

  'fields' =>array(
    'first-name' => array(
      'id' => 'first-name',
      'slug' => 'first-name',
      'type' => 'textfield',
      'name' => 'First Name',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
          'required' => array(
            'active' => 1,
            'value' => true,
            'message' => 'This field is required',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-first-name',
      'meta_type' => 'postmeta',
    ),
    'last-name' => array(
      'id' => 'last-name',
      'slug' => 'last-name',
      'type' => 'textfield',
      'name' => 'Last Name',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
          'required' => array(
            'active' => 1,
            'value' => true,
            'message' => 'This field is required',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-last-name',
      'meta_type' => 'postmeta',
    ),
    'display-name' => array(
      'id' => 'display-name',
      'slug' => 'display-name',
      'type' => 'textfield',
      'name' => 'Display Name',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-display-name',
      'meta_type' => 'postmeta',
    ),
    'email' => array(
      'id' => 'email',
      'slug' => 'email',
      'type' => 'email',
      'name' => 'Email',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
          'required' => array(
            'active' => 1,
            'value' => true,
            'message' => 'This field is required',
          ),
          'email' => array(
            'active' => 1,
            'message' => 'Please enter a valid email address',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-email',
      'meta_type' => 'postmeta',
    ),
    'phone' => array(
      'id' => 'phone',
      'slug' => 'phone',
      'type' => 'phone',
      'name' => 'Phone',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-phone',
      'meta_type' => 'postmeta',
    ),
    'mobile' => array(
      'id' => 'mobile',
      'slug' => 'mobile',
      'type' => 'numeric',
      'name' => 'Mobile',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
          'number' => array( 'active' => 1 , 'message' => 'This field should be numeric' ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-mobile',
      'meta_type' => 'postmeta',
    ),
    'website' => array(
      'id' => 'website',
      'slug' => 'website',
      'type' => 'textfield',
      'name' => 'Website',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-website',
      'meta_type' => 'postmeta',
    ),
    'ukuu-job-title' => array(
      'id' => 'ukuu-job-title',
      'name' => 'Job Title',
      'slug' => 'ukuu-job-title',
      'type' => 'textfield',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-ukuu-job-title',
      'meta_type' => 'postmeta',
    ),
    'ukuu-twitter-handle' => array(
      'id' => 'ukuu-twitter-handle',
      'name' => 'Twitter Handle',
      'slug' => 'ukuu-twitter-handle',
      'type' => 'textfield',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-ukuu-twitter-handle',
      'meta_type' => 'postmeta',
    ),
    'ukuu-facebook-url' => array(
      'id' => 'ukuu-facebook-url',
      'name' => 'Facebook URL',
      'slug' => 'ukuu-facebook-url',
      'type' => 'url',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
          'url' => array(
            'active' => 1,
            'value' => true,
            'message' => 'Please enter a valid URL address',
          ),
        ),
        'disabled_by_type' => 0,
        'conditional_display' => array(),
      ),
      'meta_key' => 'wpcf-ukuu-facebook-url',
      'meta_type' => 'postmeta',
    ),
    'ukuu-date-of-birth' => array(
      'id' => 'ukuu-date-of-birth',
      'name' => 'Date Of Birth',
      'slug' => 'ukuu-date-of-birth',
      'type' => 'date',
      'description' => '',
      'data' => array(
        'date_and_time' => 'date',
        'repetitive' => 0,
        'validate' => array(
          'date' => array(
            'active' => 1 ,
            'format' => 'mdy',
            'pattern' => 'check.format',
            'message' => 'please enter a valid date',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-ukuu-date-of-birth',
      'meta_type' => 'postmeta',
    ),
    'streetaddress' => array(
      'id' => 'streetaddress',
      'slug' => 'streetaddress',
      'type' => 'textfield',
      'name' => 'Street Address',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-streetaddress',
      'meta_type' => 'postmeta',
    ),
    'streetaddress2' => array(
      'id' => 'streetaddress2',
      'slug' => 'streetaddress2',
      'type' => 'textfield',
      'name' => 'Street Address Line 2',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-streetaddress2',
      'meta_type' => 'postmeta',
    ),
    'city' => array(
      'id' => 'city',
      'slug' => 'city',
      'type' => 'textfield',
      'name' => 'City',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-city',
      'meta_type' => 'postmeta',
    ),
    'postalcode' => array(
      'id' => 'postalcode',
      'slug' => 'postalcode',
      'type' => 'textfield',
      'name' => 'Postal code',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-postalcode',
      'meta_type' => 'postmeta',
    ),
    'country' => array(
      'id' => 'country',
      'slug' => 'country',
      'type' => 'textfield',
      'name' => 'Country',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-country',
      'meta_type' => 'postmeta',
    ),
    'state' => array(
      'id' => 'state',
      'slug' => 'state',
      'type' => 'textfield',
      'name' => 'State',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-state',
      'meta_type' => 'postmeta',
    ),
    'contactimage' => array(
      'id' => 'contactimage',
      'slug' => 'contactimage',
      'type' => 'image',
      'name' => 'Contact Image',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-contactimage',
      'meta_type' => 'postmeta',
    ),
    'privacy-settings' => array(
      'id' => 'privacy-settings',
      'slug' => 'privacy-settings',
      'type' => 'checkboxes',
      'name' => 'Preferred Contact Method',
      'description' => '',
      'data' => array(
        'save_empty' => 'no',
        'options' => array('wpcf-fields-checkboxes-option-1' => array('title' => 'Phone' , 'set_value' => 'do_not_phone' , 'display' => 'value', 'display_value_not_selected' => '', 'display_value_selected' => 'Phone') ,'wpcf-fields-checkboxes-option-2' => array('title' => 'Email' , 'set_value' => 'do_not_email' , 'display' => 'value', 'display_value_not_selected' => '', 'display_value_selected' => 'Email'),'wpcf-fields-checkboxes-option-3' => array('title' => 'Mail' , 'set_value' => 'do_not_mail' , 'display' => 'db'),'wpcf-fields-checkboxes-option-3' => array('title' => 'SMS' , 'set_value' => 'do_not_sms' , 'display' => 'value', 'display_value_not_selected' => '', 'display_value_selected' => 'SMS') ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-priority',
      'meta_type' => 'postmeta',
    ),
    'bulk-mailings' => array(
      'id' => 'bulk-mailings',
      'slug' => 'bulk-mailing',
      'type' => 'checkboxes',
      'name' => 'Bulk Mailings',
      'description' => '',
      'data' => array(
        'save_empty' => 'no',
        'options' => array('wpcf-fields-checkboxes-option-1' => array('title' => 'Opt Out' , 'set_value' => 'opt_out' , 'display' => 'value', 'display_value_not_selected' => '', 'display_value_selected' => 'Opt Out') ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-priority',
      'meta_type' => 'postmeta',
    ),
    'startdate' => array(
      'id' => 'startdate',
      'slug' => 'startdate',
      'type' => 'date',
      'name' => 'Start Date',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'date_and_time' => 'and_time',
        'validate' => array(
          'required' => array(
            'active' => 1,
            'value' => true,
            'message' => 'This field is required',
          ),
          'date' => array(
            'active' => 1 ,
            'format' => 'mdy',
            'pattern' => 'check.format',
            'message' => 'please enter a valid date',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-startdate',
      'meta_type' => 'postmeta',
    ),
    'enddate' => array(
      'id' => 'enddate',
      'slug' => 'enddate',
      'type' => 'date',
      'name' => 'End Date',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'date_and_time' => 'and_time',
        'validate' => array(
          'required' => array(
            'active' => 1,
            'value' => true,
            'message' => 'This field is required',
          ),
          'date' => array(
            'active' => 1 ,
            'format' => 'mdy',
            'pattern' => 'check.format',
            'message' => 'please enter a valid date',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-enddate',
      'meta_type' => 'postmeta',
    ),
    'status' => array(
      'id' => 'status',
      'slug' => 'status',
      'type' => 'select',
      'name' => 'Status',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'options' => array('1' => array('title' => 'Scheduled' , 'value' => 'scheduled') , 'default' => 1 ,'2' => array('title' => 'Completed' , 'value' => 'completed'),'3' => array('title' => 'Cancelled' , 'value' => 'cancelled')  ),
        'validate' => array(
          'required' => array(
            'active' => 1,
            'value' => true,
            'message' => 'This field is required',
          ),
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-status',
      'meta_type' => 'postmeta',
    ),
    'details' => array(
      'id' => 'details',
      'slug' => 'details',
      'type' => 'textarea',
      'name' => 'Details',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-details',
      'meta_type' => 'postmeta',
    ),
    'attachments' => array(
      'id' => 'attachments',
      'slug' => 'attachments',
      'type' => 'file',
      'name' => 'Attachments',
      'description' => '',
      'data' => array(
        'repetitive' => 0,
        'validate' => array(
        ),
        'conditional_display' => array(),
        'disabled_by_type' => 0,
      ),
      'meta_key' => 'wpcf-attachments',
      'meta_type' => 'postmeta',
    ),
  ),

  "field_groups" => array(
    "1" => array(
      "id" => 1,
      "key" => 'wp_activity_contacts',
      "slug" => 'wp_activity_contacts',
      "name" => 'Assigned to',
      "description" => 'Contacts reference field',
      "repeatable" => 1,
      "fields" => array(
        "1" => array(
          "name" => 'Assigned to',
          "slug" => 'wp_activity_assigned_contact',
          "description" => '',
          "type" => 'post',
          "options" => array(
            "divider" => array(
              "appearance" => 'line',
            ),
            "date_v2" => array(
              "show_as" => 'date',
              "show" => 'always',
              "default_date" => 'no_date',
            ),
            "text" => array(
              "subtype" => 'text',
              "placeholder" => '',
              "attributes" => '',
            ),
            "textarea" => array(
              "placeholder" => '',
            ),
          ),
          "type_textarea_options" => array(
            "size_height" => 'default',
          ),
          "type_post_options" => array(
            "enabled_post_types" => array(
              "0" => 'wp-type-contacts',
            ),
            "additional_arguments" => 'post_status=publish,private',
            "enable_extended_return_values" => 1,
          ),
          "type_taxonomyterm_options" => array(
            "additional_arguments" => '',
          ),
          "type_dropdown_options" => array(
            "enable_multiple" => 0,
          ),
          "id" => 1,
          "deleted" => 0,
          "field_group" => array(
            "id" => 1,
            "name" => 'Assigned to',
            "slug" => 'wp_activity_contacts',
            "description" => 'wp-contacts reference field',
            "repeatable" => 1,
            "fields_count" => 1,
          ),
        ),
      ),
      "fields_by_slug" => array(
        "assigned to" => array(
          "slug" => 'assigned',
          "name" => 'Assigned to',
          "description" => '',
          "type" => 'post',
          "options" => array(
            "post" => array(
              "enabled_post_types" => array(
                "0" => 'wp-type-contacts',
              ),
              "values" => array( ),
              "additional_arguments" => '',
              "enable_extended_return_values" => 1,
            ),
          ),
          "id" => 0,
          "type_post_options" => array(
            "enabled_post_types" => array(
              "0" => 'wp-type-contacts',
            ),
            "additional_arguments" => '',
            "enable_extended_return_values" => 1,
          ),
          "type_taxonomyterm_options" => array(
            "additional_arguments" => '',
          ),
          "deleted" => 0,
        ),
      ),
      "deleted" => '',
      "gui_view" => 'list',
      "added_with_code" => 1,
      "fields_count" => 1,
    ),
    "2" => array(
      "id" => 2,
      "key" => 'wp_type_contacts_org_relation',
      "slug" => 'wp_type_contacts_org_relation',
      "name" => 'Related Organization',
      "description" => '',
      "repeatable" => '',
      "fields" => array(
        "0" => array(
          "name" => 'Organization',
          "slug" => 'wp_type_conatcts_org',
          "description" => 'Organization term description',
          "type" => 'post',
          "options" => array(
            "divider" => array(
              "appearance" => 'line',
            ),
            "date_v2" => array(
              "show_as" => 'date',
              "show" => 'always',
              "default_date" => 'no_date',
            ),
            "text" => array(
              "subtype" => 'text',
              "placeholder" => '',
              "attributes" => '',
            ),
            "textarea" => array(
              "placeholder" => '',
            ),
          ),
          "type_textarea_options" => array(
            "size_height" => 'default',
          ),
          "type_post_options" => array(
            "enabled_post_types" => array(
              "0" => 'wp-type-contacts',
            ),
            "additional_arguments" => 'wp-type-contacts-subtype=wp-type-org-contact&post_status=publish,private',
            "enable_extended_return_values" => 1,
          ),
          "type_taxonomyterm_options" => array(
            "additional_arguments" => '',
          ),
          "type_dropdown_options" => array(
            "enable_multiple" => 0,
          ),
          "id" => 0,
          "deleted" => 0,
          "field_group" => array(
            "id" => 2,
            "name" => 'Related Organization',
            "slug" => 'wp_type_contacts_org_relation',
            "description" => '',
            "repeatable" => '',
            "fields_count" => 1,
          ),
        ),
      ),
      "fields_by_slug" => array(
        "organization" => array(
          "slug" => 'organization',
          "name" => 'Organization',
          "description" => 'Organization term description',
          "type" => 'post',
          "options" => array(
            "post" => array(
              "enabled_post_types" => array(
                "0" => 'wp-type-contacts',
              ),
              "values" => array( ),
              "additional_arguments" => '',
              "enable_extended_return_values" => 1,
            ),
          ),
          "id" => 0,
          "type_post_options" => array(
            "enabled_post_types" => array(
              "0" => 'wp-type-contacts',
            ),
            "additional_arguments" => '',
            "enable_extended_return_values" => 1,
          ),
          "type_taxonomyterm_options" => array(
            "additional_arguments" => '',
          ),
          "deleted" => 0,
        ),
      ),
      "deleted" => '',
      "gui_view" => 'list',
      "added_with_code" => 1,
      "fields_count" => 1,
    ),
  ),
  "post_connectors" => array(
    "1" => array(
      "id" => 1,
      "key" => 'wp_type_activity_related_fields',
      "slug" => 'wp_type_activity_related_fields',
      "name" => 'Activity related fields',
      "field_groups" => array(
        "1" => array(
          "id" => 1,
          "name" => 'Activity Contacts',
          "deleted" => 0,
          "context" => 'normal',
          "priority" => 'low',
        ),
      ),
      "post_types" => array(
        "0" => 'wp-type-activity',
      ),
      "deleted" => '',
      "hide_editor" => 1,
      "added_with_code" => '',
      "field_groups_count" => 2,
    ),
    "2" => array(
      "id" => 2,
      "key" => 'wp_type_contacts_related_fields',
      "slug" => 'wp_type_contacts_related_fields',
      "name" => 'Contacts related fields',
      "field_groups" => array(
        "2" => array(
          "id" => 2,
          "name" => 'Related Organization',
          "deleted" => 0,
          "context" => 'normal',
          "priority" => 'low',
        ),
      ),
      "post_types" => array(
        "0" => 'wp-type-contacts',
      ),
      "deleted" => '',
      "hide_editor" => '',
      "added_with_code" => '',
      "field_groups_count" => 2,
    ),
  ),
  "post_type_defaults" => array(
    "wp-type-activity" => 1,
    "wp-type-contacts" => 2,
  ),

);
